//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifleri_Sitem_MasterPage
{


    public partial class Tarifler
    {

        protected global::System.Web.UI.WebControls.Panel Panel1;

        protected global::System.Web.UI.WebControls.Button Button1;

        protected global::System.Web.UI.WebControls.Button Button2;

        protected global::System.Web.UI.WebControls.Panel Panel2;

        protected global::System.Web.UI.WebControls.DataList DataList1;

        protected global::System.Web.UI.WebControls.Panel Panel3;

        protected global::System.Web.UI.WebControls.Button Button3;

        protected global::System.Web.UI.WebControls.Button Button4;

        protected global::System.Web.UI.WebControls.Panel Panel4;

        protected global::System.Web.UI.WebControls.DataList DataList2;
    }
}
