//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifleri_Sitem_MasterPage
{


    public partial class TarifOner
    {

        protected global::System.Web.UI.WebControls.TextBox TxtTarifAd;

        protected global::System.Web.UI.WebControls.TextBox TxtMalzemeler;

        protected global::System.Web.UI.WebControls.TextBox TxtYapilis;

        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

        protected global::System.Web.UI.WebControls.TextBox TxtTarifOneren;

        protected global::System.Web.UI.WebControls.TextBox TxtMailAdresi;

        protected global::System.Web.UI.WebControls.Button BtnTarifOner;
    }
}
