//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifleri_Sitem_MasterPage
{


    public partial class YemekDetay
    {

        protected global::System.Web.UI.WebControls.Label Label3;

        protected global::System.Web.UI.WebControls.DataList DataList2;

        protected global::System.Web.UI.WebControls.Panel Panel1;

        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        protected global::System.Web.UI.WebControls.TextBox TextBox2;

        protected global::System.Web.UI.WebControls.TextBox TextBox3;

        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
